### ISSUE TITLE
Ensure all resources have memory requests and limits

### ISSUE THREAD

**Issue by moshloop** [flanksource/karina#393]
- sealed secrets
- cert-manager (limits)
- tekton
- harbor
- nginx
- vault
- node-local

**Comment by Aamir-raza-1** [comment]
I'll generate PR

**Comment by Aamir-raza-1** [comment]
@moshloop 
What kind of resource reqs/limits needs to be applied i mean QoS classes such as Guaranteed ,Burstable & BestEffort
 Any specific criteria or sugestion.
 
Please suggest Implementation :
Option 1)
Manually added resource requests yamls to manifest.
Option 2)
Configured  VPA autoscaler for each component. (Available in karina)
Option 3)
If we have to use resource quota and limit range for each components (harbor)

 Concerns:
i) Each environment has different kind of limitations such as kind cluster should have minimal resource request limits as compared to vpshere or provision on  cloud for HA

ii) Karina overall hardware requirements  to setup because  memory limits related to above mentioned components are accumulated into single estimated limit example
harbor mem-limit 2gb
nginx mem-limt 1gb ...
karina = 3 gb ( harbor + nginx) + ....
so target cluster should support hardware reqs for all the karina components

**Comment by moshloop** [comment]
Option 1. 

These system type resources are going to have fairly narrow resource requirements -

The defaults should be what is applicable to a standard small cluster (< 20 nodes) for everything else patches are used to increase or decrease limits as required:

https://github.com/flanksource/karina/blob/master/test/patch1.yaml
