### ISSUE TITLE
Fix CI?

### ISSUE THREAD

**Issue by tobernguyen** [flanksource/karina#667]
CI is failing for all PRs.

1. Which one do we want to fix?
2. Which one is no longer needed/relevant and we want to remove?
3. Do we want to enforce only allow merging on PR passes all CI or not?

**Comment by moshloop** [comment]
We have enforced merge blocking for only the minimal object suites - Other tests do occasionally fail e.g. https://github.com/flanksource/karina/issues/669 and some are broken due to the environment https://github.com/flanksource/karina/issues/670 

All of these tests are needed (in fact we need more) - We do have ongoing work to improve test visibility https://github.com/flanksource/karina/pull/624
